services:
  - type: web
    name: txopela-api
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn txopela_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: txopito_ia_db
      - key: GEMINI_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: dozv8vbuc
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://txopela-tour.vercel.app,https://txopela-admin.vercel.app,https://txopela-business.vercel.app
